version: '3'

services:
  backend:
    env_file:
        "./portfolio-backend/.env"
    build:
      context: ./portfolio-backend
      dockerfile: ./Dockerfile
    ports:
      - "4000:4000"
  
  frontend:
    build:
      context: ./portfolio-frontend
      dockerfile: ./Dockerfile
    ports:
      - "3000:3000"
    links:
      - "backend:be"